from sympy.combinatorics.named_groups import SymmetricGroup
from sympy.combinatorics import PermutationGroup
from enum import Enum

from enum import Enum
class IsomorphismClass(Enum):
    TRIVIAL = 1
    Z2 = 2
    KLEIN4 = 3
    Z4 = 4
    D8 = 5
    Z6 = 7
    S3 = 8
    S3Z3 = 9
    A4 = 10
    S4 = 11
    Z5 = 12
    D10 = 13
    GA = 14
    S5 = 15


class AutomorphismClass:
    @property
    def Elements(self):
        return self._permutation_group._elements

    @property
    def IsomorphismClass(self):
        return self._isomorphism_class

    @property
    def Order(self):
        return self._order

    @property
    def Index(self):
        return self._index

    def __init__(self, permutation_group, isomorphism_class, order, index):
        self._permutation_group = permutation_group
        self._isomorphism_class = isomorphism_class
        self._order = order
        self._index = index

class Sym5(PermutationGroup):
    def __init__(self):
        sym5 = SymmetricGroup(5)
        base.__init__(sym5._elements)

    def Trivial():
        return AutomorphismClass(PermutationGroup([]), IsomorphismClass.TRIVIAL, 1, 120)

    def S2():
        return AutomorphismClass(PermutationGroup([1, 0, 2, 3, 4]), IsomorphismClass.Z2, 2, 60)

    def Dbl_Transpositions1():
        return AutomorphismClass(PermutationGroup([1, 0, 3, 2, 4]), IsomorphismClass.Z2, 2, 60)

    def Dbl_Transpositions2():
        return AutomorphismClass(PermutationGroup([1, 0, 2, 3, 4], [0, 1, 3, 2, 4], [1, 0, 3, 2, 4]), IsomorphismClass.KLEIN4, 4, 30)

    def Dbl_Transpositions3():
        return AutomorphismClass(PermutationGroup([1, 0, 3, 2, 4], [2, 3, 0, 1, 4], [3, 2, 1, 0, 4]), IsomorphismClass.KLEIN4, 4, 30)

    def Z4():
        return AutomorphismClass(PermutationGroup([4, 0, 1, 2, 3], [2, 3, 0, 1, 4], [1, 2, 3, 0, 4]), IsomorphismClass.Z4, 4, 30)

    def D8():
        return AutomorphismClass(PermutationGroup([4, 0, 1, 2, 3], [1, 1, 0, 3, 4]), IsomorphismClass.D8, 8, 15)

    def Z3():
        return AutomorphismClass(PermutationGroup([2, 0, 1, 3, 4], [1, 2, 0, 3, 4]), IsomorphismClass.Z3, 3, 40)

    def Z6():
        return AutomorphismClass(PermutationGroup([2, 0, 1, 2, 4], [0, 1, 2, 4, 3]), IsomorphismClass.Z6, 6, 20)

    def S3():
        return AutomorphismClass(PermutationGroup([2, 0, 1, 3, 4], [1, 0, 2, 3, 4]), IsomorphismClass.S3, 6, 20)

    def TwistedS3():
        return AutomorphismClass(PermutationGroup([2, 0, 1, 3, 4], [1, 0, 2, 4, 3]), IsomorphismClass.S3, 6, 20)

    def S3S2():
        return AutomorphismClass(PermutationGroup([2, 0, 1, 3, 4], [1, 0, 2, 3, 4], [0, 1, 2, 4, 3]), IsomorphismClass.S3Z3, 12, 10)

    def A4():
        return AutomorphismClass(PermutationGroup([1, 0, 3, 2, 4], [2, 0, 1, 3, 4]), IsomorphismClass.A4, 12, 10)

    def S4():
        return AutomorphismClass(PermutationGroup([4, 0, 1, 2, 3], [0, 1, 2, 3, 4]), IsomorphismClass.S4, 24, 5)

S4 in S5 	\langle (1,2,3,4), (1,2) \rangle 	symmetric group:S4 	24 	5 	1 	5 	5 	(2,3)-Hall
Z5 in S5 	\langle (1,2,3,4,5) \rangle 	cyclic group:Z5 	5 	24 	1 	6 	6 	5-Sylow
D10 in S5 	\langle (1,2,3,4,5), (2,5)(3,4) \rangle 	dihedral group:D10 	10 	12 	1 	6 	6 	
GA(1,5) in S5 	\langle (1,2,3,4,5), (2,3,5,4) \rangle 	general affine group:GA(1,5) 	20 	6 	1 	6 	6 	
A5 in S5 	\langle (1,2,3,4,5), (1,2,3)\rangle 	alternating group:A5 	60 	2 	1 	1 	1 	only proper nontrivial normal subgroup, quotient is cyclic group:Z2
whole group 	\langle (1,2,3,4,5), (1,2) \rangle 	symmetric group:S5 	120 	1 	1 	1 	1 	
subgroup generated by double transpositions on four elements in S5 	\{ (), (1,2)(3,4), (1,3)(2,4), (1,4)(2,3) \} 	Klein four-group 	4 	30 	1 	5 	5 	
Z4 in S5 	\{ (), (1,2,3,4), (1,3)(2,4), (1,4,3,2) \} 	cyclic group:Z4 	4 	30 	1 	15 	15 	
D8 in S5 	\langle (1,2,3,4), (1,3) \rangle 	dihedral group:D8 	8 	15 	1 	15 	15 	2-Sylow
Z3 in S5 	\{ (), (1,2,3), (1,3,2) \} 	cyclic group:Z3 	3 	40 	1 	10 	10 	3-Sylow
Z6 in S5 	\langle (1,2,3), (4,5) \rangle 	cyclic group:Z6 	6 	20 	1 	10 	10 	
S3 in S5 	\langle (1,2,3), (1,2) \rangle 	symmetric group:S3 	6 	20 	1 	10 	10 	
twisted S3 in S5 	\langle (1,2,3), (1,2)(4,5) \rangle 	symmetric group:S3 	6 	20 	1 	10 	10 	
direct product of S3 and S2 in S5 	\langle (1,2,3), (1,2), (4,5) \rangle 	direct product of S3 and Z2 	12 	10 	1 	10 	10 	3-Sylow normalizer
A4 in S5 	\langle (1,2)(3,4), (1,2,3) \rangle 	alternating group:A4 	12 	10 	1 	5 	5 	
S4 in S5 	\langle (1,2,3,4), (1,2) \rangle 	symmetric group:S4 	24 	5 	1 	5 	5 	(2,3)-Hall
Z5 in S5 	\langle (1,2,3,4,5) \rangle 	cyclic group:Z5 	5 	24 	1 	6 	6 	5-Sylow
D10 in S5 	\langle (1,2,3,4,5), (2,5)(3,4) \rangle 	dihedral group:D10 	10 	12 	1 	6 	6 	
GA(1,5) in S5 	\langle (1,2,3,4,5), (2,3,5,4) \rangle 	general affine group:GA(1,5) 	20 	6 	1 	6 	6 	
A5 in S5 	\langle (1,2,3,4,5), (1,2,3)\rangle 	alternating group:A5 	60 	2 	1 	1 	1 	only proper nontrivial normal subgroup, quotient is cyclic group:Z2
whole group 	

"""